# Generated by Django 4.2.26 on 2026-04-24 04:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_section'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Section',
        ),
    ]
